### ISSUE TITLE
Request: Ability to increase line height

### ISSUE THREAD

**Issue by mgasparel** [omsharp/LinePress#2]
Hi, just wanted to throw out a feature request. I've been looking for an addon that could increase my line height, similar to what I can do in VS Code. 

I just want to be able to specify a default line height, that all lines will use.

I haven't done any addon development, but would be willing to give it a shot if you are open to a PR for this feature. Thoughts?

**Comment by omsharp** [comment]
Hey,

Actually, @manfredk is working on this feature at the time being, he is almost done with a working version. Just waiting for his pull request.

**Comment by mgasparel** [comment]
Good to hear! I'll keep an eye out!

**Comment by manfredk** [comment]
Hi Omar,

suffering time restrictions currently ... hoping to pr the tried and tested
changes today.

Regards,
Manfred

**Comment by manfredk** [comment]
@omsharp @mgasparel 

line spacing feature is done, pull is requested.

**Comment by omsharp** [comment]
Hey, @mgasparel @manfredk 

The latest build with the new feature is available on [Open VSIX Gallery](http://vsixgallery.com/extension/13d97f3e-75e2-4715-a444-715b5f39f0a4/)

I'll role out a new version on the market place as soon as I can. I just need to work on the description and make some screen shots and such.

**Comment by mgasparel** [comment]
Just gave it a spin! Works great!
