### ISSUE TITLE
Line spacing is broken in VS 2019 (New build is included in reply)

### ISSUE THREAD

**Issue by hwooo** [omsharp/LinePress#7]
### Installed product versions
- Visual Studio 2019 Community

### Description
- Install the plugin to VS 2019

![lines](https://user-images.githubusercontent.com/46282492/55686514-370f5500-599d-11e9-8acf-9e7444243062.PNG)

In VS 2019, line spacing is not constant.

**Comment by omsharp** [comment]
What do you mean by "broken" and "not constant"? I can't see what's wrong in the partial screenshot you shared here!

Include more details please!

**Comment by hwooo** [comment]
There was a lack of explanation. I have no problem in code itself, but as you can see, line numbers are displayed at irregular intervals. Can you reproduce this issue?

**Comment by augustincalin** [comment]
I think the problem is that deactivating Compress Empty Lines and Compress Lines with Specific Content is not working properly.
You can set these off but the empty lines (and the lines containing brackets) are still compressed.

![line-press-options](https://user-images.githubusercontent.com/9014136/55716363-11af3500-59f7-11e9-9cd4-47a4a0f0797b.PNG)

**Comment by hwooo** [comment]
Yeah, @augustincalin is right. The line contains closing braces is always compressed and I can't change it in the option.
![lines](https://user-images.githubusercontent.com/46282492/55738202-9df64200-5a61-11e9-81dc-5954e0290691.PNG)

**Comment by iKlsR** [comment]
For me, the settings for the compress lines options revert when I close the dialog or click another option so my empty lines are always compressed and the compress options aren't applied either since I tried setting them to 0. So maybe a persistence issue of sorts?

**Comment by iKlsR** [comment]
@omsharp Any ideas or a hint where to look so someone could possibly make a PR? Really hard to use VS without this ext.

**Comment by NDelt** [comment]
@iKlsR Unfortunately, this project seems not maintained anymore...

**Comment by jeongkyu** [comment]
@iKlsR  I've spent a while to debug this issue and found that the following modification make LinePress work in VS 2019. 

[fix-lost-settings.txt](https://github.com/omsharp/LinePress/files/3487609/fix-lost-settings.txt)

**Comment by NDelt** [comment]
@jeongkyu How about make a PR with it?

**Comment by iKlsR** [comment]
Thank you @jeongkyu, it works! Ok so I'm not a C# man but using latest Visual Studio I installed the C# build tools and tried to build. Failed naturally so this is how I fixed it.

1. In the **Solution Explorer**, right click the **LinePress** project and go to **Properties**. Next go to **Application** and set the *Target framework* to the latest that you have, mine is *4.7.2*.

2. Expand References and delete 
    - `Microsoft.VisualStudio.Text.Data`
    - `Microsoft.VisualStudio.Text.Logic`
    - `Microsoft.VisualStudio.CoreUtility`

3. Right click **References**, **Add Reference** and under **Assemblies** go to **Extensions**. Re-add the deleted entries above (they are the latest and need to match your target framework) and also add `Microsoft.VisualStudio.Utilities`.

4. Build

This thread was useful https://social.msdn.microsoft.com/Forums/vstudio/en-US/2b2cd3cc-2291-4935-8e9a-3382a61df53f/getting-an-quotassembly-microsoftvisualstudiotextlogic-version-14000-be-installed-in-the?forum=winformssetup

The full patch

```
diff --git a/LinePress/Options/Infrastructure/SettingsStore.cs b/LinePress/Options/Infrastructure/SettingsStore.cs
index 1c62cae..f7de1a7 100644
--- a/LinePress/Options/Infrastructure/SettingsStore.cs
+++ b/LinePress/Options/Infrastructure/SettingsStore.cs
@@ -53,23 +53,23 @@ namespace LinePress.Options
                 {
                     case bool b:
                         store.SetBoolean(settings.Key, prop.Name, b);
-                        return true;
+                        break;
 
                     case int i:
                         store.SetInt32(settings.Key, prop.Name, i);
-                        return true;
+                        break;
 
                     case double d:
                         store.SetString(settings.Key, prop.Name, d.ToString());
-                        return true;
+                        break;
 
                     case string s:
                         store.SetString(settings.Key, prop.Name, s);
-                        return true;
+                        break;
                 }
             }
 
-            return false;
+            return true;
         }
 
         private static void LoadSettingsFromStore(ISettings settings)
```

Release Build &mdash; Install at your own risk, you don't know me I guess for a disclaimer... 
[LinePress.zip](https://github.com/omsharp/LinePress/files/3489002/LinePress.zip)

**Comment by hwooo** [comment]
@iKlsR Thanks. It works like a charm!

**Comment by omsharp** [comment]
Hi,

I'm sorry, I was really busy and not being able to update the extension sooner.

I released an update that should fix this issue.

The problem was in the _SaveSettingsIntoStore_ method, I refactored the method earlier and introduced a bug without realizing.
