### ISSUE TITLE
VS 2017 doesnt save settings

### ISSUE THREAD

**Issue by pointcache** [omsharp/LinePress#8]
### Installed product versions
- Visual Studio: 2017 community, win10
- This extension: 2.3.38

### Description
Changing settings in options effectively does nothing. 

### Current behavior
It only visually shows changes, in reality it doesnt save those between vs sessions nor applies to text.

### Expected behavior
Should save and basically work.

**Comment by giovinazzo-kevin** [comment]
+1

**Comment by pedrotalespin** [comment]
+1

**Comment by iKlsR** [comment]
Hey guys, not sure if this will help but see https://github.com/omsharp/LinePress/issues/7#issuecomment-520155941

**Comment by omsharp** [comment]
Please download the latest release.
